/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalNewRouteImport } from './routes/journal.new'
import { Route as JournalIdIndexRouteImport } from './routes/journal.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIdIndexRoute = JournalIdIndexRouteImport.update({
  id: '/journal/$id/',
  path: '/journal/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/$id/': typeof JournalIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/$id': typeof JournalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/$id/': typeof JournalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/journal/new' | '/journal/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/journal/new' | '/journal/$id'
  id: '__root__' | '/' | '/journal/new' | '/journal/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalNewRoute: typeof JournalNewRoute
  JournalIdIndexRoute: typeof JournalIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$id/': {
      id: '/journal/$id/'
      path: '/journal/$id'
      fullPath: '/journal/$id/'
      preLoaderRoute: typeof JournalIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalNewRoute: JournalNewRoute,
  JournalIdIndexRoute: JournalIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
